metadata-objects/extracted/unpackaged/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IRPF__c</fullName>
        <label>IRPF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IVA__c</fullName>
        <label>IVA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IssueDate__c</fullName>
        <label>Fecha de emisión</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pedido</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requiv__c</fullName>
        <label>R.equiv.</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de Cobro</fullName>
                    <default>true</default>
                    <label>Pendiente de Cobro</label>
                </value>
                <value>
                    <fullName>Cobrada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaxBase__c</fullName>
        <label>Base imponible</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Total factura</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Número de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <recordTypes>
        <fullName>Correctora</fullName>
        <active>true</active>
        <description>Factura correctora que anula la factura original</description>
        <label>Correctora</label>
    </recordTypes>
    <recordTypes>
        <fullName>Original</fullName>
        <active>true</active>
        <description>Factura original emitida</description>
        <label>Original</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>Descrip__c</fullName>
        <label>Descrip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Factura</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Líneas de factura</relationshipLabel>
        <relationshipName>InvoiceItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Precio(EUR/l)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de factura</relationshipLabel>
        <relationshipName>InvoiceItem</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Línea de factura</label>
    <nameField>
        <displayFormat>LF-{0}</displayFormat>
        <label>Línea de factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>A3Status__c</fullName>
        <label>Estado de A3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Enviado</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Modificar Pedido</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Error Envío</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Pedido Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinalAmount__c</fullName>
        <label>Importe Final</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Nº de Factura</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>Fecha del pedido</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Pdte envío a Planta</fullName>
                </value>
                <value>
                    <fullName>Enviado a Planta</fullName>
                </value>
                <value>
                    <fullName>Fuera de Planta</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Caducado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaxBase__c</fullName>
        <label>Base Imponible</label>
        <summarizedField>OrderItem__c.TotalAmount__c</summarizedField>
        <summaryForeignKey>OrderItem__c.Pedido__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <recordTypes>
        <fullName>Corrector</fullName>
        <active>true</active>
        <description>Pedido corrector con valores negativos para anular el pedido original</description>
        <label>Corrector</label>
    </recordTypes>
    <recordTypes>
        <fullName>Original</fullName>
        <active>true</active>
        <description>Pedido original</description>
        <label>Original</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rectificado</fullName>
        <active>true</active>
        <description>Pedido rectificado que puede ser modificado por el usuario</description>
        <label>Rectificado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Pedido__c</fullName>
        <label>Pedido</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descripción del Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <formula>Quantity__c  *  UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Precio €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Línea de pedido</label>
    <nameField>
        <displayFormat>LP-{0}</displayFormat>
        <label>Nº línea de pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/extracted/unpackaged/classes/InvoiceRectificationControllerDebugPage.cls
/**
 * @description Controller para la página de rectificación de facturas con debug
 * @author Sistema de Rectificación HAFESA
 * @date 2024
 */
public with sharing class InvoiceRectificationControllerDebugPage {
    
    public String errorMessage { get; set; }
    public String loadingMessage { get; set; }
    public String successMessage { get; set; }
    
    /**
     * @description Método que se ejecuta automáticamente al cargar la página
     */
    public PageReference rectifyInvoice() {
        try {
            // Obtener el ID de la factura desde los parámetros de la URL
            String invoiceId = ApexPages.currentPage().getParameters().get('id');
            
            if (String.isBlank(invoiceId)) {
                errorMessage = 'No se proporcionó el ID de la factura';
                return null;
            }
            
            loadingMessage = 'Iniciando proceso de rectificación...';
            
            // Ejecutar la lógica de rectificación directamente
            String rectifiedOrderId = executeRectificationProcess(invoiceId);
            
            successMessage = 'Proceso de rectificación completado. Redirigiendo al pedido rectificado.';
            
            // Redirigir al pedido rectificado
            PageReference pageRef = new PageReference('/' + rectifiedOrderId);
            pageRef.setRedirect(true);
            return pageRef;
            
        } catch (Exception e) {
            errorMessage = 'Error en el proceso de rectificación: ' + e.getMessage();
            System.debug('Error en rectifyInvoice: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
            return null;
        }
    }
    
    /**
     * @description Método @AuraEnabled para usar en Flow Builder
     * @param invoiceId ID de la factura a rectificar
     * @return String con el resultado de la rectificación
     */
    @AuraEnabled(cacheable=false)
    public static String executeRectificationFromFlow(String invoiceId) {
        try {
            // Obtener el ID del pedido desde la factura
            Invoice__c invoice = [SELECT Order__c FROM Invoice__c WHERE Id = :invoiceId LIMIT 1];
            
            if (invoice.Order__c == null) {
                throw new AuraHandledException('La factura no tiene un pedido asociado');
            }
            
            // Llamar al método que ya sabemos que funciona con el ID del pedido
            String result = executeRectificationProcess(invoice.Order__c);
            return 'SUCCESS: ' + result;
        } catch (Exception e) {
            return 'ERROR: ' + e.getMessage();
        }
    }

    /**
     * @description Ejecuta el proceso de rectificación con el código que sabemos que funciona
     */
    @AuraEnabled(cacheable=false)
    public static String executeRectificationProcess(String invoiceId) {
        try {
            System.debug('=== INICIO PROCESO RECTIFICACIÓN ===');
            System.debug('Invoice ID: ' + invoiceId);
            
            // Verificar permisos básicos
            if (!Schema.sObjectType.Order__c.isCreateable()) {
                throw new AuraHandledException('No tiene permisos para crear pedidos');
            }
            
            // Obtener la factura original
            Invoice__c originalInvoice = [
                SELECT Id, Name, Order__c, TotalAmount__c, TaxBase__c, IVA__c, IRPF__c, Requiv__c, IssueDate__c, Account__c
                FROM Invoice__c
                WHERE Id = :invoiceId
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            
            System.debug('Factura obtenida: ' + originalInvoice.Name);
            
            // Verificar que la factura tenga un pedido asociado
            if (originalInvoice.Order__c == null) {
                throw new AuraHandledException('La factura no tiene un pedido asociado');
            }
            
            // Obtener el pedido original
            Order__c originalOrder = [
                SELECT Id, Name, FinalAmount__c, OrderDate__c, Status__c, A3Status__c, InvoiceNumber__c, Account__c
                FROM Order__c
                WHERE Id = :originalInvoice.Order__c
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            
            System.debug('Pedido obtenido: ' + originalOrder.Name);
            
            // 1. Crear pedido corrector
            Order__c correctorOrder = new Order__c();
            // Name field is auto-generated, don't set it
            correctorOrder.FinalAmount__c = -originalOrder.FinalAmount__c;
            correctorOrder.OrderDate__c = Date.today();
            correctorOrder.Status__c = 'Nuevo'; 
            correctorOrder.A3Status__c = null;
            correctorOrder.InvoiceNumber__c = null;
            correctorOrder.Account__c = originalOrder.Account__c;
            
            System.debug('Insertando pedido corrector...');
            insert correctorOrder;
            System.debug('Pedido corrector creado: ' + correctorOrder.Id);
            
            // 2. Crear factura correctora
            Invoice__c correctorInvoice = new Invoice__c();
            // Name field is auto-generated, don't set it
            correctorInvoice.Order__c = correctorOrder.Id;
            correctorInvoice.Account__c = originalInvoice.Account__c;
            correctorInvoice.TotalAmount__c = -originalInvoice.TotalAmount__c;
            correctorInvoice.TaxBase__c = -originalInvoice.TaxBase__c;
            correctorInvoice.IVA__c = -originalInvoice.IVA__c;
            correctorInvoice.IRPF__c = originalInvoice.IRPF__c != null ? -originalInvoice.IRPF__c : 0;
            correctorInvoice.Requiv__c = originalInvoice.Requiv__c != null ? -originalInvoice.Requiv__c : 0;
            correctorInvoice.IssueDate__c = Date.today();
            
            System.debug('Insertando factura correctora...');
            insert correctorInvoice;
            System.debug('Factura correctora creada: ' + correctorInvoice.Id);
            
            // 3. Crear pedido rectificado
            Order__c rectifiedOrder = new Order__c();
            // Name field is auto-generated, don't set it
            rectifiedOrder.FinalAmount__c = originalOrder.FinalAmount__c;
            rectifiedOrder.OrderDate__c = Date.today();
            rectifiedOrder.Status__c = 'Nuevo';
            rectifiedOrder.A3Status__c = null;
            rectifiedOrder.InvoiceNumber__c = null;
            rectifiedOrder.Account__c = originalOrder.Account__c;
            
            System.debug('Insertando pedido rectificado...');
            insert rectifiedOrder;
            System.debug('Pedido rectificado creado: ' + rectifiedOrder.Id);
            
            // 4. Clonar productos del pedido corrector (valores negativos)
            cloneOrderItems(correctorOrder.Id, originalOrder.Id, true);
            
            // 5. Clonar productos del pedido rectificado (valores positivos)
            cloneOrderItems(rectifiedOrder.Id, originalOrder.Id, false);
            
            // 6. Clonar productos de la factura correctora (valores negativos)
            cloneInvoiceItems(correctorInvoice.Id, originalInvoice.Id, true);
            
            System.debug('=== PROCESO COMPLETADO EXITOSAMENTE ===');
            System.debug('RESULTADOS:');
            System.debug('- Pedido Corrector ID: ' + correctorOrder.Id);
            System.debug('- Factura Correctora ID: ' + correctorInvoice.Id);
            System.debug('- Pedido Rectificado ID: ' + rectifiedOrder.Id);
            
            return rectifiedOrder.Id;
            
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error en rectificación: ' + e.getMessage());
        }
    }
    
    /**
     * @description Clona los productos de un pedido
     */
    private static void cloneOrderItems(Id newOrderId, Id originalOrderId, Boolean isNegative) {
        try {
            List<OrderItem__c> originalItems = [
                SELECT Id, Name, Quantity__c, UnitPrice__c, ProductDescription__c
                FROM OrderItem__c
                WHERE Pedido__c = :originalOrderId
                WITH SECURITY_ENFORCED
            ];
            
            if (!originalItems.isEmpty()) {
                List<OrderItem__c> newItems = new List<OrderItem__c>();
                for (OrderItem__c item : originalItems) {
                    OrderItem__c newItem = new OrderItem__c();
                    newItem.Pedido__c = newOrderId;
                    newItem.ProductDescription__c = item.ProductDescription__c;
                    newItem.Quantity__c = isNegative ? -item.Quantity__c : item.Quantity__c;
                    newItem.UnitPrice__c = isNegative ? -item.UnitPrice__c : item.UnitPrice__c;
                    newItems.add(newItem);
                }
                insert newItems;
                System.debug('Productos de pedido clonados: ' + newItems.size() + ' items');
            }
        } catch (Exception e) {
            System.debug('Error clonando productos de pedido: ' + e.getMessage());
        }
    }
    
    /**
     * @description Clona los productos de una factura
     */
    private static void cloneInvoiceItems(Id newInvoiceId, Id originalInvoiceId, Boolean isNegative) {
        try {
            List<InvoiceItem__c> originalItems = [
                SELECT Id, Name, Quantity__c, Price__c, Product__c, Descrip__c
                FROM InvoiceItem__c
                WHERE Invoice__c = :originalInvoiceId
                WITH SECURITY_ENFORCED
            ];
            
            if (!originalItems.isEmpty()) {
                List<InvoiceItem__c> newItems = new List<InvoiceItem__c>();
                for (InvoiceItem__c item : originalItems) {
                    InvoiceItem__c newItem = new InvoiceItem__c();
                    newItem.Invoice__c = newInvoiceId;
                    newItem.Product__c = item.Product__c;
                    newItem.Descrip__c = item.Descrip__c;
                    newItem.Quantity__c = isNegative ? -item.Quantity__c : item.Quantity__c;
                    newItem.Price__c = isNegative ? -item.Price__c : item.Price__c;
                    newItems.add(newItem);
                }
                insert newItems;
                System.debug('Productos de factura clonados: ' + newItems.size() + ' items');
            }
        } catch (Exception e) {
            System.debug('Error clonando productos de factura: ' + e.getMessage());
        }
    }
}