metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinalAmount__c</fullName>
        <label>Importe Final</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>Fecha del pedido</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Pdte envío a Planta</fullName>
                </value>
                <value>
                    <fullName>Enviado a Planta</fullName>
                </value>
                <value>
                    <fullName>Fuera de Planta</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Caducado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestSimple.cls
/**
 * @description Clase de prueba ultra-simple
 * @author Sistema de Rectificación HAFESA
 * @date 2024
 */
public class TestSimple {
    
    /**
     * @description Método ultra-simple para probar
     */
    public static void testBasic() {
        try {
            System.debug('=== INICIO TEST BÁSICO ===');
            
            // Solo crear un pedido simple
            Order__c testOrder = new Order__c();
            testOrder.FinalAmount__c = 100;
            testOrder.OrderDate__c = Date.today();
            testOrder.Status__c = 'Nuevo';
            testOrder.Account__c = '001dt0000000T0hAAE'; // Usar un Account válido
            
            System.debug('Insertando pedido de prueba...');
            insert testOrder;
            
            System.debug('Pedido creado exitosamente: ' + testOrder.Id);
            System.debug('=== TEST COMPLETADO ===');
            
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
        }
    }
}