metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvocablePedidosA3Test.cls
@IsTest
public class InvocablePedidosA3Test {
	@IsTest
    public static void EnviarPedidoTest(){
        Account acc = new Account(Name='Test');
        insert acc;
        
        Order__c newOrder = new Order__c(Account__c=acc.id);
        insert newOrder; 
        
        list<Id> Ordenes = new list<Id>();
        Ordenes.add(newOrder.Id);
        
        Test.startTest();
        	InvocablePedidosA3.EnviarPedido(Ordenes);
        Test.stopTest();
    }
}