metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FreightOder__c</fullName>
        <label>Orden de Carga</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderHandlerTest.cls
@IsTest
public with sharing class OrderHandlerTest {

    @TestSetup
	private static void makeData(){
        Account newAccount = new Account(Name='Cliente', Email__c='test@test.test');
        insert newAccount;
        Order__c newOrder = new Order__c(Account__c=newAccount.Id);
        insert newOrder;
    }

    @IsTest
    public static void handleAfterUpdateTest(){
        Order__c updateOrder = [SELECT id FROM Order__c LIMIT 1];
        updateOrder.FreightOder__c = '000000';
        update updateOrder;
    }
}