force-app/main/default/objects/Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Empresa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Energía</fullName>
                </value>
                <value>
                    <fullName>Suministro</fullName>
                </value>
                <value>
                    <fullName>Distribución</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transportista</label>
    <nameField>
        <label>Transportista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>A3Status__c</fullName>
        <label>Estado de A3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Enviado</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Modificar Pedido</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Error Envío</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Pedido Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <formula>TEXT(Account__r.Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Empresa</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transportista</label>
        <referenceTo>Carrier__c</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryNoteNumber__c</fullName>
        <label>Nº de Albarán</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalAmount__c</fullName>
        <label>Importe Final</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FreightDate__c</fullName>
        <label>Fecha de carga</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Nº de Factura</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margen</label>
        <summarizedField>OrderItem__c.Margin__c</summarizedField>
        <summaryForeignKey>OrderItem__c.Pedido__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>Fecha del pedido</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Nº Pedido A3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <label>Forma de pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethod</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlantStatus__c</fullName>
        <label>Estado de Planta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>(Sin Estado)</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Pendiente (Planta)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Fuera de Planta</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Cargando</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Incompleta</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Albarán</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Cancelada</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Fin Manual</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Caducada</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Plataforma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Platform</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proforma__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proforma</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale15__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Venta a 15º</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serie__c</fullName>
        <label>Serie</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Pdte envío a Planta</fullName>
                </value>
                <value>
                    <fullName>Enviado a Planta</fullName>
                </value>
                <value>
                    <fullName>Fuera de Planta</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Caducado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Almacén</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Store</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaxBase__c</fullName>
        <label>Base Imponible</label>
        <summarizedField>OrderItem__c.TotalAmount__c</summarizedField>
        <summaryForeignKey>OrderItem__c.Pedido__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <recordTypes>
        <fullName>Original</fullName>
        <active>true</active>
        <description>Pedido original</description>
        <label>Original</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>BasePrice__c</fullName>
        <label>Precio Base €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BaseTotal__c</fullName>
        <formula>BasePrice__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Base</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <formula>TotalAmount__c -  BaseTotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margen</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimalPrice__c</fullName>
        <label>Precio Mínimo €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimalTotal__c</fullName>
        <formula>MinimalPrice__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Mínimo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pedido__c</fullName>
        <label>Pedido</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <formula>ProductDescription__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código del producto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descripción del Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <formula>Quantity__c  *  UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Precio €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Línea de pedido</label>
    <nameField>
        <displayFormat>LP-{0}</displayFormat>
        <label>Nº línea de pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderCloneController.cls
/**
 * @description Controller para clonar pedidos (Order__c)
 * @author José María Porras
 * @date 2025-09-30
 */
public with sharing class OrderCloneController {
    
    /**
     * @description Clona un pedido existente con los campos especificados y sus líneas
     * @param originalOrderId ID del pedido original a clonar
     * @return ID del nuevo pedido clonado
     */
    @AuraEnabled(cacheable=false)
    public static String cloneOrder(String originalOrderId) {
        try {
            // Verificar que el usuario tenga permisos para crear pedidos
            if (!Schema.sObjectType.Order__c.isCreateable()) {
                throw new AuraHandledException('No tiene permisos para crear pedidos');
            }
            
            // Obtener el pedido original con todos los campos necesarios
            Order__c originalOrder = [
                SELECT Id, Name, OrderNumber__c, OrderDate__c, Account__c, 
                       Business__c, Store__c, Platform__c, PaymentMethod__c,
                       FinalAmount__c, TaxBase__c, Margin__c, Status__c,
                       Carrier__c, FreightDate__c, DeliveryNoteNumber__c,
                       InvoiceNumber__c, Proforma__c, Serie__c, A3Status__c,
                       PlantStatus__c, Sale15__c
                FROM Order__c 
                WHERE Id = :originalOrderId 
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            
            // Crear el nuevo pedido clonado
            Order__c clonedOrder = originalOrder.clone(false, true, false, false);
            
            // Modificar campos específicos para el pedido clonado
            clonedOrder.OrderNumber__c = null; // Se generará automáticamente
            clonedOrder.OrderDate__c = Date.today();
            clonedOrder.Status__c = 'Nuevo'; // Estado inicial
            clonedOrder.A3Status__c = null;
            clonedOrder.PlantStatus__c = null;
            clonedOrder.DeliveryNoteNumber__c = null;
            clonedOrder.InvoiceNumber__c = null;
            clonedOrder.FreightDate__c = null;
            
            // Insertar el nuevo pedido
            insert clonedOrder;
            
            // Buscar y clonar las líneas de pedido relacionadas
            cloneOrderLines(originalOrderId, clonedOrder.Id);
            
            return clonedOrder.Id;
            
        } catch (QueryException e) {
            throw new AuraHandledException('Error al obtener el pedido: ' + e.getMessage());
        } catch (DmlException e) {
            throw new AuraHandledException('Error al crear el pedido clonado: ' + e.getMessage());
        } catch (Exception e) {
            throw new AuraHandledException('Error inesperado: ' + e.getMessage());
        }
    }
    
    /**
     * @description Clona las líneas de pedido relacionadas
     * @param originalOrderId ID del pedido original
     * @param clonedOrderId ID del pedido clonado
     */
    private static void cloneOrderLines(String originalOrderId, String clonedOrderId) {
        try {
            System.debug('=== INICIANDO CLONACIÓN DE LÍNEAS DE PEDIDO ===');
            System.debug('Order ID original: ' + originalOrderId);
            System.debug('Order ID clonado: ' + clonedOrderId);
            
            // Usar el objeto correcto: OrderItem__c con el campo Pedido__c
            List<OrderItem__c> originalLines = [
                SELECT Id, Pedido__c, Name, ProductCode__c, ProductDescription__c, 
                       Quantity__c, UnitPrice__c, TotalAmount__c, BasePrice__c, 
                       BaseTotal__c, Margin__c, MinimalPrice__c, MinimalTotal__c
                FROM OrderItem__c 
                WHERE Pedido__c = :originalOrderId 
                WITH SECURITY_ENFORCED
            ];
            
            System.debug('Líneas encontradas: ' + originalLines.size());
            
            if (!originalLines.isEmpty()) {
                List<OrderItem__c> clonedLines = new List<OrderItem__c>();
                
                for (OrderItem__c originalLine : originalLines) {
                    OrderItem__c clonedLine = originalLine.clone(false, true, false, false);
                    clonedLine.Pedido__c = clonedOrderId;
                    clonedLines.add(clonedLine);
                    
                    System.debug('Clonando línea: ' + originalLine.Name + ' -> ' + clonedLine.Name);
                }
                
                insert clonedLines;
                System.debug('✅ Líneas clonadas exitosamente: ' + clonedLines.size());
            } else {
                System.debug('ℹ️  No hay líneas de pedido para clonar');
            }
            
            System.debug('=== FIN DE CLONACIÓN DE LÍNEAS ===');
        } catch (Exception e) {
            System.debug('❌ Error clonando líneas de pedido: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error al clonar las líneas de pedido: ' + e.getMessage());
        }
    }
    
    
    /**
     * @description Obtiene los detalles de un pedido para mostrar en el modal de confirmación
     * @param orderId ID del pedido
     * @return Objeto Order__c con los campos necesarios
     */
    @AuraEnabled(cacheable=true)
    public static Order__c getOrderDetails(String orderId) {
        try {
            return [
                SELECT Id, Name, OrderNumber__c, OrderDate__c, Account__c, 
                       Business__c, Store__c, Platform__c, PaymentMethod__c,
                       FinalAmount__c, Status__c, CreatedDate
                FROM Order__c 
                WHERE Id = :orderId 
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error al obtener detalles del pedido: ' + e.getMessage());
        }
    }
    
    // Variables para la página Visualforce
    public String loadingMessage { get; set; }
    public String errorMessage { get; set; }
    
    /**
     * @description Constructor para la página Visualforce
     */
    public OrderCloneController() {
        // Constructor vacío
    }
    
    /**
     * @description Método de acción para la página Visualforce
     */
    public PageReference cloneOrder() {
        try {
            String originalOrderId = ApexPages.currentPage().getParameters().get('recordId');
            
            if (String.isBlank(originalOrderId)) {
                errorMessage = 'No se encontró el ID del pedido a clonar';
                return null;
            }
            
            loadingMessage = 'Clonando pedido...';
            
            // Ejecutar la clonación
            String clonedOrderId = cloneOrder(originalOrderId);
            
            if (String.isNotBlank(clonedOrderId)) {
                // Redirigir al pedido clonado
                PageReference pageRef = new PageReference('/' + clonedOrderId);
                pageRef.setRedirect(true);
                return pageRef;
            } else {
                errorMessage = 'No se pudo crear el pedido clonado';
                return null;
            }
            
        } catch (Exception e) {
            errorMessage = 'Error al clonar el pedido: ' + e.getMessage();
            return null;
        }
    }
    
    /**
     * @description Método de diagnóstico que devuelve información sobre las líneas de pedido
     * @param orderId ID del pedido a diagnosticar
     * @return Información del diagnóstico
     */
    @AuraEnabled(cacheable=false)
    public static String diagnoseOrderLines(String orderId) {
        try {
            String result = '=== DIAGNÓSTICO AVANZADO DE LÍNEAS DE PEDIDO ===\n';
            result += 'Order ID: ' + orderId + '\n\n';
            
            // Probar directamente con el objeto correcto: OrderItem__c
            result += '🔍 BUSCANDO LÍNEAS DE PEDIDO...\n';
            result += 'Probando con el objeto correcto: OrderItem__c\n\n';
            
            boolean found = false;
            
            try {
                // Contar registros
                String countQuery = 'SELECT COUNT() FROM OrderItem__c WHERE Pedido__c = :orderId';
                Integer totalCount = Database.countQuery(countQuery);
                
                if (totalCount > 0) {
                    result += '✅ ¡ENCONTRADO! Objeto "OrderItem__c" con campo "Pedido__c"\n';
                    result += '   Total de registros: ' + totalCount + '\n\n';
                    
                    // Obtener detalles de los primeros registros
                    List<OrderItem__c> detailResults = [
                        SELECT Id, Name, ProductCode__c, ProductDescription__c, 
                               Quantity__c, UnitPrice__c, TotalAmount__c
                        FROM OrderItem__c 
                        WHERE Pedido__c = :orderId 
                        LIMIT 5
                    ];
                    
                    result += '   Detalles de los primeros registros:\n';
                    for (OrderItem__c record : detailResults) {
                        result += '   - ID: ' + record.Id + ', Name: ' + record.Name + '\n';
                        result += '     Producto: ' + record.ProductDescription__c + '\n';
                        result += '     Cantidad: ' + record.Quantity__c + ', Precio: ' + record.UnitPrice__c + '\n';
                    }
                    found = true;
                } else {
                    result += 'ℹ️  No se encontraron líneas de pedido en OrderItem__c\n';
                }
                
            } catch (Exception e) {
                result += '❌ Error consultando OrderItem__c: ' + e.getMessage() + '\n';
            }
            
            if (!found) {
                result += '❌ NO SE ENCONTRARON LÍNEAS DE PEDIDO\n';
                result += 'Posibles causas:\n';
                result += '1. No hay líneas de pedido en este pedido específico\n';
                result += '2. No hay permisos para acceder a las líneas\n';
                result += '3. El pedido aún no tiene líneas asociadas\n';
            }
            
            result += '\n=== FIN DEL DIAGNÓSTICO ===';
            return result;
            
        } catch (Exception e) {
            return 'Error en diagnóstico: ' + e.getMessage();
        }
    }

    @InvocableMethod(label='Clonar Pedido' description='Clona un pedido y todas sus líneas de pedido relacionadas.')
    public static List<String> cloneOrderInvocable(List<String> orderIds) {
        List<String> results = new List<String>();
        for (String orderId : orderIds) {
            try {
                String clonedOrderId = cloneOrder(orderId);
                results.add(clonedOrderId);
            } catch (Exception e) {
                results.add('ERROR: ' + e.getMessage());
            }
        }
        return results;
    }
}