force-app/main/default/objects/Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Empresa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Energía</fullName>
                </value>
                <value>
                    <fullName>Suministro</fullName>
                </value>
                <value>
                    <fullName>Distribución</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CarrierCode__c</fullName>
        <label>Código transportista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transportista</label>
    <nameField>
        <label>Transportista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <formula>TEXT(Account__r.Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Empresa</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transportista</label>
        <referenceTo>Carrier__c</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpirationDateTime__c</fullName>
        <label>Fecha de caducidad</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>Fecha del pedido</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Nº Pedido A3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <label>Forma de pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethod</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale15__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Venta a 15º</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Almacén</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Store</valueSetName>
        </valueSet>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Pedido__c</fullName>
        <label>Pedido</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descripción del Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Precio €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Línea de pedido</label>
    <nameField>
        <displayFormat>LP-{0}</displayFormat>
        <label>Nº línea de pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/extracted/unpackaged/classes/InvocablePedidosA3.cls
public class InvocablePedidosA3 {
    @InvocableMethod(label='Enviar Pedidos a A3' description='Se envian los pedidos a A3')
    public static void EnviarPedido(List<string> recordId){
        sObject obj = [SELECT id,PaymentMethod__c,Name,Account__r.Business__c,Account__r.ClientCodeA3__c,Account__r.Parent.RepresentativeCode__c,Account__r.RepresentativeCode__c,OrderNumber__c,Store__c,Carrier__r.CarrierCode__c,Sale15__c,OrderDate__c,ExpirationDateTime__c,OwnerId,
                       (
                           SELECT id,ProductDescription__r.Id,ProductDescription__r.Name,ProductDescription__r.ProductCode,ProductDescription__r.Description,Quantity__c,UnitPrice__c 
                           FROM Lineas_de_pedido__r
                       ) 
                       FROM Order__c 
                       WHERE id = :recordId[0] Order by Name asc];
        
        QueueCallA3Service newQueue = new QueueCallA3Service(recordId[0], 'POST', 'Order', obj, 50000);
        System.enqueueJob(newQueue);
    }
}