force-app/main/default/objects/Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <label>Empresa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Energía</fullName>
                </value>
                <value>
                    <fullName>Suministro</fullName>
                </value>
                <value>
                    <fullName>Distribución</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CarrierCode__c</fullName>
        <label>Código transportista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transportista</label>
    <nameField>
        <label>Transportista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-objects/extracted/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <formula>TEXT(Account__r.Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Empresa</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transportista</label>
        <referenceTo>Carrier__c</referenceTo>
        <relationshipLabel>Pedidos</relationshipLabel>
        <relationshipName>Pedidos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpirationDateTime__c</fullName>
        <label>Fecha de caducidad</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrderDate__c</fullName>
        <label>Fecha del pedido</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PaymentMethod__c</fullName>
        <label>Forma de pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethod</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sale15__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Venta a 15º</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Almacén</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Store</valueSetName>
        </valueSet>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Número de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Pedido__c</fullName>
        <label>Pedido</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descripción del Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Precio €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Línea de pedido</label>
    <nameField>
        <displayFormat>LP-{0}</displayFormat>
        <label>Nº línea de pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateOrderScreenFlowControllerTest.cls
@isTest
global with sharing class UpdateOrderScreenFlowControllerTest {
    
    @TestSetup
    static void makeData(){
        Account acc = new Account(Name='Name',CIF__c='0001',ClientCodeA3__c='1',Business__c='Suministro',BillingStreet='Calle',BillingPostalCode='0001',BillingCountry='Pais',BillingState='Provincia',BillingCity='City',Phone='666555444',TaxRate__c='1');
        insert acc;
        Carrier__c carr = new Carrier__c(Name='Name',CarrierCode__c='0000');
        insert carr;
        Order__c ord = new Order__c(PaymentMethod__c = 'C',Account__c=acc.id,Store__c='TORREJON',Carrier__c=carr.id,OrderDate__c=Date.today(),ExpirationDateTime__c=Date.today(),Sale15__c=true);
        insert ord;
        Product2 prod = new Product2(Name='Name');
        insert prod;
        OrderItem__c item = new OrderItem__c(Pedido__c=ord.id,ProductDescription__c=prod.id,Quantity__c=1,UnitPrice__c=1);
        insert item;
        
    }

    @isTest 
    global static void test1(){
        Order__c order = [SELECT PaymentMethod__c,Account__c,Store__c,Carrier__c,OrderDate__c,ExpirationDateTime__c,Sale15__c FROM Order__c LIMIT 1];
        List<OrderItem__c> listItems = [SELECT Pedido__c,ProductDescription__c,Quantity__c,UnitPrice__c,ProductDescription__r.Name FROM OrderItem__c];
        test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

            UpdateOrderScreenFlowController.callOutA3(order,listItems,'test');
        test.stopTest();
    }
    @isTest 
    global static void test2(){
        Order__c order = [SELECT PaymentMethod__c,Account__c,Store__c,Carrier__c,OrderDate__c,ExpirationDateTime__c,Sale15__c FROM Order__c LIMIT 1];
        String testData = 'test;'+order.Id;
        test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

            UpdateOrderScreenFlowController.getAccountNames(new List<String>{testData});
        test.stopTest();
    }
    global class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            System.assertEquals('https://example.com/example/test', req.getEndpoint());
            System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }
}