force-app/main/default/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>BasePrice__c</fullName>
        <label>Precio Base €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimalPrice__c</fullName>
        <label>Precio Mínimo €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductDescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Descripción del Producto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Líneas de pedido</relationshipLabel>
        <relationshipName>Lineas_de_pedido</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Cantidad(l)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Precio €/l</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Línea de pedido</label>
    <nameField>
        <displayFormat>LP-{0}</displayFormat>
        <label>Nº línea de pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LwcOrderItemTable.cls
public with sharing class LwcOrderItemTable {
    
    @AuraEnabled
    public static List<wrapperData> getOrderItems(List<String> listIds){
        List<OrderItem__c> newListOrderItems = [SELECT Name,BasePrice__c,MinimalPrice__c,UnitPrice__c,Quantity__c,ProductDescription__r.Name FROM OrderItem__c WHERE ID in:listIds Order by ProductDescription__r.Name asc];
        List<wrapperData> listWrp = new List<wrapperData>();
        for(OrderItem__c ord: newListOrderItems){
            wrapperData wrp = new wrapperData(ord);
            
            listWrp.add(wrp);
        }
        System.debug('listWrp: ' + listWrp);
        return listWrp;
    }


    public class wrapperData{
        @AuraEnabled public String Id_Salesforce { get; set;}
        @AuraEnabled public String Name { get; set;}
        @AuraEnabled public Decimal Quantity { get; set;}
        @AuraEnabled public Decimal UnitPrice  { get; set;}
        @AuraEnabled public String ProductDescription{get;set;}
        public  wrapperData(OrderItem__c ord){
            Id_Salesforce = ord.Id;
            Name = ord.Name;
            Quantity = ord.Quantity__c;
            UnitPrice = ord.UnitPrice__c;
            ProductDescription = ord.ProductDescription__r.Name;
            
        }
        
    }
}